const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
const CLEAR_CART = 'CLEAR_CART'; 
const TOGGLE_CART = 'TOGGLE_CART';

module.exports = {
  UPDATE_PRODUCTS,
  ADD_TO_CART,
  UPDATE_CART_QUANTITY,
  REMOVE_FROM_CART,
  ADD_MULTIPLE_TO_CART,
  UPDATE_CATEGORIES,
  UPDATE_CURRENT_CATEGORY,
  CLEAR_CART,
  TOGGLE_CART
}