const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
const CLEAR_CART = 'CLEAR_CART'; 
const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY';
const INVENTORY_CHECK = 'INVENTORY_CHECK';
const REMOVE_FROM_INVENTORY = 'REMOVE_FROM_INVENTORY';
const TOGGLE_CART = 'TOGGLE_CART';
const CLOSE_CART = 'CLOSE_CART';
const UPDATE_USERS = 'UPDATE_USERS';

module.exports = {
  UPDATE_PRODUCTS,
  UPDATE_USERS,
  ADD_TO_CART,
  UPDATE_CART_QUANTITY,
  CLEAR_CART,
  TOGGLE_CART,
  CLOSE_CART,
  ADD_TO_INVENTORY,
  INVENTORY_CHECK,
  REMOVE_FROM_INVENTORY
}